sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install coverage detox tox-travis flake8

script:
  - coverage erase
  - detox
  - flake8 django_cache_friendly_timestamp_signer/

after_success:
  - coverage combine --append
  - coverage report -m
  - pip install codecov
  - codecov
